In [ ]:
#https://github.com/allisgoodrn/guided1/raw/main/data2.csv
#do I have pandas
!pip show pandas
# if I do not:
#!pip install pandas

In [1]:
#call pandas 
import pandas as pd #'pd' is a nickname
#use a function from pandas to read the cloud data into a python object
gitCloudGuided1='https://github.com/allisgoodrn/guided1/raw/main/'
worldPoplReviewCost='data2.csv'

In [2]:
DFcsv=pd.read_csv(gitCloudGuided1 + worldPoplReviewCost)

In [3]:
DFcsv.columns.to_list()

['fips',
 'state',
 'densityMi',
 'pop2023',
 'pop2022',
 'pop2020',
 'pop2019',
 'pop2010',
 'growthRate',
 'growth',
 'growthSince2010',
 'name',
 'id',
 'costIndex',
 'groceryCost',
 'housingCost',
 'utilitiesCost',
 'transportationCost',
 'miscCost']

In [4]:
bye=[0,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18]
DFcsv.drop(columns=DFcsv.columns[bye],inplace=True)

In [5]:
DFcsv

             state  costIndex
0      Mississippi       83.3
1           Kansas       86.5
2          Alabama       87.9
3         Oklahoma       87.9
4          Georgia       88.8
5        Tennessee       89.0
6         Missouri       89.8
7             Iowa       89.9
8    West Virginia       90.5
9          Indiana       90.6
10        Arkansas       90.9
11      New Mexico       91.0
12        Michigan       91.3
13            Ohio       91.3
14           Texas       92.1
15       Louisiana       93.0
16        Kentucky       93.1
17  South Carolina       93.6
18        Nebraska       93.7
19        Illinois       94.3
20         Wyoming       94.3
21  North Carolina       95.7
22       Wisconsin       96.4
23    North Dakota       98.2
24            Utah       99.0
25       Minnesota      100.0
26         Florida      100.3
27         Montana      100.7
28    South Dakota      101.0
29        Virginia      101.8
30           Idaho      102.1
31    Pennsylvania      102.5
32         Arizona      103.2
33        Colorado      105.3
34          Nevada      106.3
35        Delaware      107.9
36   New Hampshire      109.9
37      Washington      111.6
38           Maine      115.0
39      New Jersey      115.2
40         Vermont      117.0
41    Rhode Island      117.2
42     Connecticut      121.6
43        Maryland      124.0
44          Alaska      127.1
45          Oregon      130.1
46   Massachusetts      135.0
47      California      142.2
48        New York      148.2
49          Hawaii      193.3

In [6]:
DFcsv.loc[:,"state"]

0        Mississippi
1             Kansas
2            Alabama
3           Oklahoma
4            Georgia
5          Tennessee
6           Missouri
7               Iowa
8      West Virginia
9            Indiana
10          Arkansas
11        New Mexico
12          Michigan
13              Ohio
14             Texas
15         Louisiana
16          Kentucky
17    South Carolina
18          Nebraska
19          Illinois
20           Wyoming
21    North Carolina
22         Wisconsin
23      North Dakota
24              Utah
25         Minnesota
26           Florida
27           Montana
28      South Dakota
29          Virginia
30             Idaho
31      Pennsylvania
32           Arizona
33          Colorado
34            Nevada
35          Delaware
36     New Hampshire
37        Washington
38             Maine
39        New Jersey
40           Vermont
41      Rhode Island
42       Connecticut
43          Maryland
44            Alaska
45            Oregon
46     Massachusetts
47        California
48          New York
49            Hawaii
Name: state, dtype: object

In [7]:
DFcsv=DFcsv.sort_values(by=["state"], inplace= False, ascending=True)

In [8]:
DFcsv.reset_index(drop=True, inplace=True)
DFcsv

             state  costIndex
0          Alabama       87.9
1           Alaska      127.1
2          Arizona      103.2
3         Arkansas       90.9
4       California      142.2
5         Colorado      105.3
6      Connecticut      121.6
7         Delaware      107.9
8          Florida      100.3
9          Georgia       88.8
10          Hawaii      193.3
11           Idaho      102.1
12        Illinois       94.3
13         Indiana       90.6
14            Iowa       89.9
15          Kansas       86.5
16        Kentucky       93.1
17       Louisiana       93.0
18           Maine      115.0
19        Maryland      124.0
20   Massachusetts      135.0
21        Michigan       91.3
22       Minnesota      100.0
23     Mississippi       83.3
24        Missouri       89.8
25         Montana      100.7
26        Nebraska       93.7
27          Nevada      106.3
28   New Hampshire      109.9
29      New Jersey      115.2
30      New Mexico       91.0
31        New York      148.2
32  North Carolina       95.7
33    North Dakota       98.2
34            Ohio       91.3
35        Oklahoma       87.9
36          Oregon      130.1
37    Pennsylvania      102.5
38    Rhode Island      117.2
39  South Carolina       93.6
40    South Dakota      101.0
41       Tennessee       89.0
42           Texas       92.1
43            Utah       99.0
44         Vermont      117.0
45        Virginia      101.8
46      Washington      111.6
47   West Virginia       90.5
48       Wisconsin       96.4
49         Wyoming       94.3