In [ ]:
#!pip show pandas

In [1]:
import pandas as pd
gitCloudGuided='https://github.com/allisgoodrn/guided1/raw/main/'
worldPoplReview='data1.csv'
##
gitCloudGuided1='https://github.com/allisgoodrn/guided1/raw/main/'
worldPoplReviewCost='data2.csv'

In [2]:
## fetching our data
DFcsv1=pd.read_csv(gitCloudGuided + worldPoplReview)
DFcsv2=pd.read_csv(gitCloudGuided1 + worldPoplReviewCost)

In [3]:
## these are the columns shared among the DFs
set(DFcsv1.columns) &set(DFcsv2)

{'fips', 'state'}

In [4]:
DFcsv1.columns.to_list()

['State',
 'FIPS',
 'Total',
 'NonHispanic',
 'WhiteNonHispanic',
 'BlackNonHispanic',
 'IndianNonHispanic',
 'AsianNonHispanic',
 'HawaiianNonHispanic',
 'OtherNonHispanic',
 'TwoOrMoreNonHispanic',
 'Hispanic',
 'WhiteHispanic',
 'BlackHispanic',
 'IndianHispanic',
 'AsianHispanic',
 'HawaiianHispanic',
 'OtherHispanic',
 'TwoOrMoreHispanic',
 'state',
 'fips',
 'WhiteTotal',
 'BlackTotal',
 'IndianTotal',
 'AsianTotal',
 'HawaiianTotal',
 'OtherTotal',
 'TwoOrMoreTotal',
 'WhiteHispanicPerc',
 'WhiteNonHispanicPerc',
 'BlackHispanicPerc',
 'BlackNonHispanicPerc',
 'IndianHispanicPerc',
 'IndianNonHispanicPerc',
 'AsianHispanicPerc',
 'AsianNonHispanicPerc',
 'HawaiianHispanicPerc',
 'HawaiianNonHispanicPerc',
 'OtherHispanicPerc',
 'OtherNonHispanicPerc',
 'TwoOrMoreHispanicPerc',
 'TwoOrMoreNonHispanicPerc',
 'WhiteTotalPerc',
 'BlackTotalPerc',
 'IndianTotalPerc',
 'AsianTotalPerc',
 'HawaiianTotalPerc',
 'OtherTotalPerc',
 'TwoOrMoreTotalPerc']

In [5]:
want=['State','Total','WhiteNonHispanic','BlackNonHispanic','IndianNonHispanic', 'AsianNonHispanic', 'Hispanic']
DFcsv1=DFcsv1.loc[:,want]

In [6]:
DFcsv1.reset_index(drop=True, inplace=True)

In [7]:
DFcsv2.columns.to_list()

['fips',
 'state',
 'densityMi',
 'pop2023',
 'pop2022',
 'pop2020',
 'pop2019',
 'pop2010',
 'growthRate',
 'growth',
 'growthSince2010',
 'name',
 'id',
 'costIndex',
 'groceryCost',
 'housingCost',
 'utilitiesCost',
 'transportationCost',
 'miscCost']

In [8]:
want2=['state','costIndex']
DFcsv2=DFcsv2.loc[:,want2]

In [9]:
DFcsv2=DFcsv2.sort_values(by=["state"], inplace= False, ascending=True)

In [10]:
complete=DFcsv1.merge(DFcsv2,right_on='state',left_on='State')#.shape

In [11]:
complete

,State,Total,WhiteNonHispanic,BlackNonHispanic,IndianNonHispanic,AsianNonHispanic,Hispanic,state,costIndex
0,Alabama,4893186,3192147,1292950,21297,67317,212951,Alabama,87.9
1,Alaska,736990,439979,22720,103843,45855,53059,Alaska,127.1
2,Arizona,7174064,3883722,305973,272294,233048,2260690,Arizona,103.2
3,Arkansas,3011873,2155099,455485,15912,45389,229629,Arkansas,90.9
4,California,39346023,14365145,2142371,131724,5743983,15380929,California,142.2
5,Colorado,5684926,3837450,224190,29337,178265,1231126,Colorado,105.3
6,Connecticut,3570549,2357942,352036,4882,161787,587212,Connecticut,121.6
7,Delaware,967679,595236,208126,2836,38249,91350,Delaware,107.9
8,Florida,21216924,11331222,3231108,39070,579476,5468826,Florida,100.3
9,Georgia,10516579,5478289,3275581,17433,430473,1013057,Georgia,88.8
10,Hawaii,1420074,306360,25130,2100,522125,152566,Hawaii,193.3
11,Idaho,1754367,1427529,10558,18866,23603,222967,Idaho,102.1
12,Illinois,12716164,7737459,1766586,13301,702457,2190696,Illinois,94.3
13,Indiana,6696893,5253453,622317,10363,157076,475475,Indiana,90.6
14,Iowa,3150011,2677946,114312,8055,78873,194407,Iowa,89.9
15,Kansas,2912619,2193988,159797,17788,85734,351602,Kansas,86.5
16,Kentucky,4461952,3751738,356048,7075,67524,167949,Kentucky,93.1
17,Louisiana,4664616,2720638,1489071,23328,79976,243372,Louisiana,93.0
18,Maine,1340825,1242113,17761,8011,15157,23143,Maine,115.0
19,Maryland,6037624,3028494,1773702,11223,382027,619418,Maryland,124.0
20,Massachusetts,6873003,4865022,466288,8943,462831,828140,Massachusetts,135.0
21,Michigan,9973907,7428622,1342592,42931,314736,521203,Michigan,91.3
22,Minnesota,5600166,4422490,354540,48409,273100,307675,Minnesota,100.0
23,Mississippi,2981835,1680938,1118689,12897,29561,94342,Mississippi,83.3
24,Missouri,6124160,4826943,692510,20646,122506,262677,Missouri,89.8
25,Montana,1061705,908782,4931,62720,8527,41501,Montana,100.7
26,Nebraska,1923826,1507127,89744,13378,47539,214952,Nebraska,93.7
27,Nevada,3030281,1460159,271744,25928,246904,875798,Nevada,106.3
28,New Hampshire,1355244,1214029,18343,1895,36398,52792,New Hampshire,109.9
29,New Jersey,8885418,4858807,1121134,10290,851568,1815078,New Jersey,115.2
30,New Mexico,2097021,769139,37975,179881,31328,1031788,New Mexico,91.0
31,New York,19514849,10766297,2737471,42429,1657284,3720707,New York,148.2
32,North Carolina,10386227,6503292,2182623,108223,306140,991051,North Carolina,95.7
33,North Dakota,760394,636284,23459,37170,11831,30325,North Dakota,98.2
34,Ohio,11675275,9141370,1422412,14901,266601,459939,Ohio,91.3
35,Oklahoma,3949342,2563119,282134,288801,85858,431467,Oklahoma,87.9
36,Oregon,4176346,3128494,75418,35842,185221,552279,Oregon,130.1
37,Pennsylvania,12794885,9685118,1352329,12224,445725,971813,Pennsylvania,102.5
38,Rhode Island,1057798,755708,58680,2832,35856,168007,Rhode Island,117.2
39,South Carolina,5091517,3230111,1337126,14085,82800,296897,South Carolina,93.6
40,South Dakota,879336,715328,18436,72142,12275,36088,South Dakota,101.0
41,Tennessee,6772268,4969371,1118600,13814,121808,377162,Tennessee,89.0
42,Texas,28635442,11850477,3367449,65132,1396953,11294257,Texas,92.1
43,Utah,3151239,2455192,34982,27734,72061,446067,Utah,99.0
44,Vermont,624340,576601,7496,1538,10042,12518,Vermont,117.0
45,Virginia,8509358,5209336,1590974,16856,564706,810770,Virginia,101.8
46,Washington,7512465,5067909,279720,75677,656578,971522,Washington,111.6
47,West Virginia,1807426,1654681,63133,3072,13948,28679,West Virginia,90.5
48,Wisconsin,5806975,4681072,360526,43830,162010,408267,Wisconsin,96.4
49,Wyoming,581348,485816,4712,11596,4746,58854,Wyoming,94.3

In [12]:
# dropping the lower case state column 
complete=complete.drop(labels= 'state',axis=1)

In [13]:
#changing the column names 
complete.rename(columns=
              {'Total':'Total_Population',
               'WhiteNonHispanic':'European',
              'BlackNonHispanic': 'African',
               'IndianNonHispanic':'Indigenous',
              'AsianNonHispanic':'Asian',
               'Hispanic':'Latinx',
               'costIndex':'Cost_Index'},inplace = True)

In [14]:
complete.columns.to_list()

['State',
 'Total_Population',
 'European',
 'African',
 'Indigenous',
 'Asian',
 'Latinx',
 'Cost_Index']

In [15]:
complete=complete[['State', 'Total_Population', 'Cost_Index', 'Indigenous','European','Latinx','African','Asian']]

In [16]:
# bye anything between parenthesis
complete.columns.str.replace('\(.+\)',"", regex=True)

Index(['State', 'Total_Population', 'Cost_Index', 'Indigenous', 'European',
       'Latinx', 'African', 'Asian'],
      dtype='object')

In [17]:
# bye anything between parenthesis, bye leading-trailing spaces
complete.columns.str.replace('\(.+\)',"", regex=True).str.strip()

Index(['State', 'Total_Population', 'Cost_Index', 'Indigenous', 'European',
       'Latinx', 'African', 'Asian'],
      dtype='object')

In [18]:
# bye anything between parenthesis, bye leading-trailing spaces, title case
complete.columns.str.replace('\(.+\)',"", regex=True).\
                          str.strip().\
                          str.title()

Index(['State', 'Total_Population', 'Cost_Index', 'Indigenous', 'European',
       'Latinx', 'African', 'Asian'],
      dtype='object')

In [20]:
#changing column names
complete.columns=complete.columns.str.replace('\(.+\)',"", regex=True).\
                          str.strip().\
                          str.title()

complete

,State,Total_Population,Cost_Index,Indigenous,European,Latinx,African,Asian
0,Alabama,4893186,87.9,21297,3192147,212951,1292950,67317
1,Alaska,736990,127.1,103843,439979,53059,22720,45855
2,Arizona,7174064,103.2,272294,3883722,2260690,305973,233048
3,Arkansas,3011873,90.9,15912,2155099,229629,455485,45389
4,California,39346023,142.2,131724,14365145,15380929,2142371,5743983
5,Colorado,5684926,105.3,29337,3837450,1231126,224190,178265
6,Connecticut,3570549,121.6,4882,2357942,587212,352036,161787
7,Delaware,967679,107.9,2836,595236,91350,208126,38249
8,Florida,21216924,100.3,39070,11331222,5468826,3231108,579476
9,Georgia,10516579,88.8,17433,5478289,1013057,3275581,430473
10,Hawaii,1420074,193.3,2100,306360,152566,25130,522125
11,Idaho,1754367,102.1,18866,1427529,222967,10558,23603
12,Illinois,12716164,94.3,13301,7737459,2190696,1766586,702457
13,Indiana,6696893,90.6,10363,5253453,475475,622317,157076
14,Iowa,3150011,89.9,8055,2677946,194407,114312,78873
15,Kansas,2912619,86.5,17788,2193988,351602,159797,85734
16,Kentucky,4461952,93.1,7075,3751738,167949,356048,67524
17,Louisiana,4664616,93.0,23328,2720638,243372,1489071,79976
18,Maine,1340825,115.0,8011,1242113,23143,17761,15157
19,Maryland,6037624,124.0,11223,3028494,619418,1773702,382027
20,Massachusetts,6873003,135.0,8943,4865022,828140,466288,462831
21,Michigan,9973907,91.3,42931,7428622,521203,1342592,314736
22,Minnesota,5600166,100.0,48409,4422490,307675,354540,273100
23,Mississippi,2981835,83.3,12897,1680938,94342,1118689,29561
24,Missouri,6124160,89.8,20646,4826943,262677,692510,122506
25,Montana,1061705,100.7,62720,908782,41501,4931,8527
26,Nebraska,1923826,93.7,13378,1507127,214952,89744,47539
27,Nevada,3030281,106.3,25928,1460159,875798,271744,246904
28,New Hampshire,1355244,109.9,1895,1214029,52792,18343,36398
29,New Jersey,8885418,115.2,10290,4858807,1815078,1121134,851568
30,New Mexico,2097021,91.0,179881,769139,1031788,37975,31328
31,New York,19514849,148.2,42429,10766297,3720707,2737471,1657284
32,North Carolina,10386227,95.7,108223,6503292,991051,2182623,306140
33,North Dakota,760394,98.2,37170,636284,30325,23459,11831
34,Ohio,11675275,91.3,14901,9141370,459939,1422412,266601
35,Oklahoma,3949342,87.9,288801,2563119,431467,282134,85858
36,Oregon,4176346,130.1,35842,3128494,552279,75418,185221
37,Pennsylvania,12794885,102.5,12224,9685118,971813,1352329,445725
38,Rhode Island,1057798,117.2,2832,755708,168007,58680,35856
39,South Carolina,5091517,93.6,14085,3230111,296897,1337126,82800
40,South Dakota,879336,101.0,72142,715328,36088,18436,12275
41,Tennessee,6772268,89.0,13814,4969371,377162,1118600,121808
42,Texas,28635442,92.1,65132,11850477,11294257,3367449,1396953
43,Utah,3151239,99.0,27734,2455192,446067,34982,72061
44,Vermont,624340,117.0,1538,576601,12518,7496,10042
45,Virginia,8509358,101.8,16856,5209336,810770,1590974,564706
46,Washington,7512465,111.6,75677,5067909,971522,279720,656578
47,West Virginia,1807426,90.5,3072,1654681,28679,63133,13948
48,Wisconsin,5806975,96.4,43830,4681072,408267,360526,162010
49,Wyoming,581348,94.3,11596,485816,58854,4712,4746

In [21]:
complete.columns.str.replace(" ",'',regex=False)

Index(['State', 'Total_Population', 'Cost_Index', 'Indigenous', 'European',
       'Latinx', 'African', 'Asian'],
      dtype='object')

In [23]:
complete.columns=complete.columns.str.replace(" ",'',regex=False)

In [25]:
complete=complete[~complete.iloc[:,1:].isna().any(axis=1)].copy()
#
complete

,State,Total_Population,Cost_Index,Indigenous,European,Latinx,African,Asian
0,Alabama,4893186,87.9,21297,3192147,212951,1292950,67317
1,Alaska,736990,127.1,103843,439979,53059,22720,45855
2,Arizona,7174064,103.2,272294,3883722,2260690,305973,233048
3,Arkansas,3011873,90.9,15912,2155099,229629,455485,45389
4,California,39346023,142.2,131724,14365145,15380929,2142371,5743983
5,Colorado,5684926,105.3,29337,3837450,1231126,224190,178265
6,Connecticut,3570549,121.6,4882,2357942,587212,352036,161787
7,Delaware,967679,107.9,2836,595236,91350,208126,38249
8,Florida,21216924,100.3,39070,11331222,5468826,3231108,579476
9,Georgia,10516579,88.8,17433,5478289,1013057,3275581,430473
10,Hawaii,1420074,193.3,2100,306360,152566,25130,522125
11,Idaho,1754367,102.1,18866,1427529,222967,10558,23603
12,Illinois,12716164,94.3,13301,7737459,2190696,1766586,702457
13,Indiana,6696893,90.6,10363,5253453,475475,622317,157076
14,Iowa,3150011,89.9,8055,2677946,194407,114312,78873
15,Kansas,2912619,86.5,17788,2193988,351602,159797,85734
16,Kentucky,4461952,93.1,7075,3751738,167949,356048,67524
17,Louisiana,4664616,93.0,23328,2720638,243372,1489071,79976
18,Maine,1340825,115.0,8011,1242113,23143,17761,15157
19,Maryland,6037624,124.0,11223,3028494,619418,1773702,382027
20,Massachusetts,6873003,135.0,8943,4865022,828140,466288,462831
21,Michigan,9973907,91.3,42931,7428622,521203,1342592,314736
22,Minnesota,5600166,100.0,48409,4422490,307675,354540,273100
23,Mississippi,2981835,83.3,12897,1680938,94342,1118689,29561
24,Missouri,6124160,89.8,20646,4826943,262677,692510,122506
25,Montana,1061705,100.7,62720,908782,41501,4931,8527
26,Nebraska,1923826,93.7,13378,1507127,214952,89744,47539
27,Nevada,3030281,106.3,25928,1460159,875798,271744,246904
28,New Hampshire,1355244,109.9,1895,1214029,52792,18343,36398
29,New Jersey,8885418,115.2,10290,4858807,1815078,1121134,851568
30,New Mexico,2097021,91.0,179881,769139,1031788,37975,31328
31,New York,19514849,148.2,42429,10766297,3720707,2737471,1657284
32,North Carolina,10386227,95.7,108223,6503292,991051,2182623,306140
33,North Dakota,760394,98.2,37170,636284,30325,23459,11831
34,Ohio,11675275,91.3,14901,9141370,459939,1422412,266601
35,Oklahoma,3949342,87.9,288801,2563119,431467,282134,85858
36,Oregon,4176346,130.1,35842,3128494,552279,75418,185221
37,Pennsylvania,12794885,102.5,12224,9685118,971813,1352329,445725
38,Rhode Island,1057798,117.2,2832,755708,168007,58680,35856
39,South Carolina,5091517,93.6,14085,3230111,296897,1337126,82800
40,South Dakota,879336,101.0,72142,715328,36088,18436,12275
41,Tennessee,6772268,89.0,13814,4969371,377162,1118600,121808
42,Texas,28635442,92.1,65132,11850477,11294257,3367449,1396953
43,Utah,3151239,99.0,27734,2455192,446067,34982,72061
44,Vermont,624340,117.0,1538,576601,12518,7496,10042
45,Virginia,8509358,101.8,16856,5209336,810770,1590974,564706
46,Washington,7512465,111.6,75677,5067909,971522,279720,656578
47,West Virginia,1807426,90.5,3072,1654681,28679,63133,13948
48,Wisconsin,5806975,96.4,43830,4681072,408267,360526,162010
49,Wyoming,581348,94.3,11596,485816,58854,4712,4746

In [26]:
# get rid of leading and trailing spaces in text cells
complete.State=complete.State.str.strip()

In [27]:
complete

,State,Total_Population,Cost_Index,Indigenous,European,Latinx,African,Asian
0,Alabama,4893186,87.9,21297,3192147,212951,1292950,67317
1,Alaska,736990,127.1,103843,439979,53059,22720,45855
2,Arizona,7174064,103.2,272294,3883722,2260690,305973,233048
3,Arkansas,3011873,90.9,15912,2155099,229629,455485,45389
4,California,39346023,142.2,131724,14365145,15380929,2142371,5743983
5,Colorado,5684926,105.3,29337,3837450,1231126,224190,178265
6,Connecticut,3570549,121.6,4882,2357942,587212,352036,161787
7,Delaware,967679,107.9,2836,595236,91350,208126,38249
8,Florida,21216924,100.3,39070,11331222,5468826,3231108,579476
9,Georgia,10516579,88.8,17433,5478289,1013057,3275581,430473
10,Hawaii,1420074,193.3,2100,306360,152566,25130,522125
11,Idaho,1754367,102.1,18866,1427529,222967,10558,23603
12,Illinois,12716164,94.3,13301,7737459,2190696,1766586,702457
13,Indiana,6696893,90.6,10363,5253453,475475,622317,157076
14,Iowa,3150011,89.9,8055,2677946,194407,114312,78873
15,Kansas,2912619,86.5,17788,2193988,351602,159797,85734
16,Kentucky,4461952,93.1,7075,3751738,167949,356048,67524
17,Louisiana,4664616,93.0,23328,2720638,243372,1489071,79976
18,Maine,1340825,115.0,8011,1242113,23143,17761,15157
19,Maryland,6037624,124.0,11223,3028494,619418,1773702,382027
20,Massachusetts,6873003,135.0,8943,4865022,828140,466288,462831
21,Michigan,9973907,91.3,42931,7428622,521203,1342592,314736
22,Minnesota,5600166,100.0,48409,4422490,307675,354540,273100
23,Mississippi,2981835,83.3,12897,1680938,94342,1118689,29561
24,Missouri,6124160,89.8,20646,4826943,262677,692510,122506
25,Montana,1061705,100.7,62720,908782,41501,4931,8527
26,Nebraska,1923826,93.7,13378,1507127,214952,89744,47539
27,Nevada,3030281,106.3,25928,1460159,875798,271744,246904
28,New Hampshire,1355244,109.9,1895,1214029,52792,18343,36398
29,New Jersey,8885418,115.2,10290,4858807,1815078,1121134,851568
30,New Mexico,2097021,91.0,179881,769139,1031788,37975,31328
31,New York,19514849,148.2,42429,10766297,3720707,2737471,1657284
32,North Carolina,10386227,95.7,108223,6503292,991051,2182623,306140
33,North Dakota,760394,98.2,37170,636284,30325,23459,11831
34,Ohio,11675275,91.3,14901,9141370,459939,1422412,266601
35,Oklahoma,3949342,87.9,288801,2563119,431467,282134,85858
36,Oregon,4176346,130.1,35842,3128494,552279,75418,185221
37,Pennsylvania,12794885,102.5,12224,9685118,971813,1352329,445725
38,Rhode Island,1057798,117.2,2832,755708,168007,58680,35856
39,South Carolina,5091517,93.6,14085,3230111,296897,1337126,82800
40,South Dakota,879336,101.0,72142,715328,36088,18436,12275
41,Tennessee,6772268,89.0,13814,4969371,377162,1118600,121808
42,Texas,28635442,92.1,65132,11850477,11294257,3367449,1396953
43,Utah,3151239,99.0,27734,2455192,446067,34982,72061
44,Vermont,624340,117.0,1538,576601,12518,7496,10042
45,Virginia,8509358,101.8,16856,5209336,810770,1590974,564706
46,Washington,7512465,111.6,75677,5067909,971522,279720,656578
47,West Virginia,1807426,90.5,3072,1654681,28679,63133,13948
48,Wisconsin,5806975,96.4,43830,4681072,408267,360526,162010
49,Wyoming,581348,94.3,11596,485816,58854,4712,4746

In [28]:
# Checking numeric columns
complete.iloc[:,1:].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Total_Population  50 non-null     int64
 1   Cost_Index        50 non-null     float64
 2   Indigenous        50 non-null     int64
 3   European          50 non-null     int64
 4   Latinx            50 non-null     int64
 5   African           50 non-null     int64
 6   Asian             50 non-null     int64
dtypes: float64(1), int64(6)
memory usage: 3.1 KB

In [29]:
complete.iloc[:,1:].max()

Total_Population    39346023.0
Cost_Index               193.3
Indigenous            288801.0
European            14365145.0
Latinx              15380929.0
African              3367449.0
Asian                5743983.0
dtype: float64

In [30]:
complete.iloc[:,1:].min()

Total_Population    581348.0
Cost_Index              83.3
Indigenous            1538.0
European            306360.0
Latinx               12518.0
African               4712.0
Asian                 4746.0
dtype: float64

In [34]:
complete=complete.copy()

In [36]:
complete.to_csv("complete.csv")